services:
  - type: web
    name: codepulse-api
    runtime: docker
    plan: free
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__CodePulseConnectionString
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        sync: false
      - key: Jwt__Audience
        sync: false
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
      - key: Cors__AllowedOrigin
        sync: false
